language: android
sudo: true

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

before_install:
  # Install fpm
  - sudo apt-get update
  - sudo apt-get install -y curl rpm
  - curl -L https://get.rvm.io | bash -s stable
  - source ~/.rvm/scripts/rvm
  - rvm reload
  - rvm requirements
  - rvm install ruby
  - rvm use ruby --default
  - rvm rubygems current
  - sleep 0.1
  - gem install fpm

script:
  - mkdir -p app/src/debug/res/values app/src/release/res/values
  - cp app/google_maps_api.xml.template app/src/debug/res/values/google_maps_api.xml
  - cp app/google_maps_api.xml.template app/src/release/res/values/google_maps_api.xml
  - ./gradlew assemble :lightsservice:release || exit 1
  - make -C service || exit 1
